/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as IndexRouteImport } from './routes/index'

const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accommodation' | '/contact' | '/gallery' | '/offers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accommodation' | '/contact' | '/gallery' | '/offers'
  id: '__root__' | '/' | '/accommodation' | '/contact' | '/gallery' | '/offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationRoute: typeof AccommodationRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OffersRoute: typeof OffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationRoute: AccommodationRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OffersRoute: OffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
